### ISSUE TITLE
Agregar dependencia para persistencia

### ISSUE THREAD

**Issue by SebasMullicundo** [SebasMullicundo/Repo_TpFinal#22]
***Descripción:***
-------------------
- Necesitamos agregar las siguientes dependencias en el archivo pom.xml del proyecto para habilitar la persistencia de entidades mediante JPA

***Tarea:***
------------
- Agregar las dependecias mysql-connector-java y spring-boot-starter-data-jpa son necesarias para utilizar JPA y establecer la conexión con una base de datos MySQL.

**Comment by daniiestefii** [comment]
Subido en una rama llamada Agergacion_depesendecias y marge a la rama principal.
Terminado
