### ISSUE TITLE
Agregar documentación de la entidad Recetas

### ISSUE THREAD

**Issue by SebasMullicundo** [SebasMullicundo/Repo_TpFinal#28]
***Descripción:***
-------------------
- Se requiere agregar la documentación correspondiente de la entidad "Recetas" para ayudar a comprender mejor el propósito, los métodos y los parámetros asociados con la entidad.

***Tareas:***
-------------
- Agregar documentación a los controladores relacionados con la entidad.

- Agregar documentación a los servicios relacionados con la entidad.

- Agregar documentación a las implementaciones relacionadas con la entidad.

- Agregar documentación adicional en otras partes del código donde considere necesario.

**Comment by daniiestefii** [comment]
Se documento todas las entidades solicitadas 
Terminado
