### ISSUE TITLE
Agregar vista para visualizar categorías de recetas

### ISSUE THREAD

**Issue by SebasMullicundo** [SebasMullicundo/Repo_TpFinal#30]
***Descripción:***
-------------------
- Se requiere agregar una nueva vista en el proyecto que permita a los usuarios ver las categorías de las recetas disponibles. Al acceder a cada categoría, se deberán mostrar las recetas correspondientes a esa categoría específica. Además, se debe permitir a los usuarios ingresar a los detalles de cada receta para ver su preparación e ingredientes.

***Tares:***
------------
- Crear una nueva vista que muestre una lista de categorías de recetas disponibles.
- Agregar un controlador que maneje las solicitudes relacionadas con las categorías de recetas.
- Crear una nueva vista que muestre las recetas correspondientes a una categoría específica seleccionada por el usuario.

**Comment by KevinChosco** [comment]
Tareas:
Crear una nueva vista que muestre una lista de categorías de recetas disponibles.
Agregar un controlador que maneje las solicitudes relacionadas con las categorías de recetas.
Crear una nueva vista que muestre las recetas correspondientes a una categoría específica seleccionada por el usuario.

Desarrollo:

Se creo un nuevo archivo HTML llamado categorias_recetas.html, donde muestra una tabla con una lista de categorías de recetas disponibles. Cada categoría se muestra como un enlace que dirige al usuario a la ruta /recetas/categoria/{categoria}, donde {categoria} es el nombre de la categoría seleccionada por el usuario.
Se agrego un nuevo método en RecetaControlle que acepta un parámetro "categoria" que indica la categoría seleccionada por el usuario. Luego, usa el método filtroRecetaCategoria del servicio recetaService para obtener la lista de recetas correspondientes a esa categoría y las agrega al modelo para que puedan ser mostradas en la vista recetas_por_categoria.html.
Se creo un nuevo archivo HTML llamado recetas_por_categorias.html que muestra una tabla con una lista de recetas correspondientes a la categoría seleccionada por el usuario. Cada receta se muestra con su nombre, categoría, ingredientes y preparación. También se muestra un enlace para ver los detalles de cada receta.
