### ISSUE TITLE
Creación de la página de lista de recetas y testimonios

### ISSUE THREAD

**Issue by SebasMullicundo** [SebasMullicundo/Repo_TpFinal#4]
***Descripción:***
--------------------
- La tarea tiene como objetivo crear las páginas recetas y testimonios dentro del proyecto.

***Recetas***
--------------
- Se debe redirigir a una página donde se muestren las diferentes propuestas de recetas.
- Las recetas deben tener una pequeñas descripción junto con una imagen para representarla.
- Cada receta debe una opción que permita tener una descripción mas completa del articulo.
- Imagen guía
![5](https://github.com/SebasMullicundo/Repo_TpFinal/assets/122728796/ab0d9e39-0eb6-4b04-911d-c4ddc0f3eaaf)

---

***Testimonios***
-------------------
- Se debe crear una página dedicada a mostrar testimonios de los usuarios sobre el sitio y sus servicios.
- Cada testimonio debe incluir el nombre del usuario.
- Se crear una opción que permita a los usuarios ingresar su testimonio.
- Imagen guía
![4](https://github.com/SebasMullicundo/Repo_TpFinal/assets/122728796/f3eafdaa-8191-4876-81ab-da73ce636701)

---

***Uso de bootstrap***
-------------------------
- Incorporar bootstrap para las páginas desarrolladas y aplicar diseño responsivo para una adecuada adaptación en diferentes tamaños de dispositivos.
- Implementar contenedores Bootstrap para estructurar el diseño.
- Utilizar filas y columnas de Bootstrap para establecer una estructura de diseño flexible y adaptable.
- Asegurar que el contenido y el diseño se adapten y se visualicen correctamente en diferentes dispositivos.

**Comment by KevinChosco** [comment]
Pagina subida, se realizo el uso de bootstrap y thymeleaf. Creando el controller para poder ver la pagina recetea.html
